### ISSUE TITLE
关于验证码提示为英文问题

### ISSUE THREAD

**Issue by sechelper** [HamZone/flarum-ext-auth-phone#1]
![图片](https://user-images.githubusercontent.com/100655242/218791796-6ad2b69b-c12b-4345-989f-44bb77d803bd.png)
![图片](https://user-images.githubusercontent.com/100655242/218791844-c64096a3-20bd-4831-a5b2-c98a674229fc.png)

希望能增加中英文提示配置，大部分实名认证需求都是国内，英文的话部分人看不懂也发不了贴，不太友好。

作者幸苦。

**Comment by sechelper** [comment]
刚才看到有关于中英文的配置，我的语言已经设置为中文未生效，我尝试修改下

**Comment by Eminlin** [comment]
这个问题我之前也有发现，暂时还没处理，临时方案可以用另外一个插件先做一下补充 https://github.com/FriendsOfFlarum/linguist

安装完之后，选择导入，选择中文简体，导入内容在https://github.com/HamZone/flarum-ext-auth-phone/blob/main/resources/locale/zh-hans.yml 

导入完成后，根据提示清楚一下缓存，就可以了

**Comment by sechelper** [comment]
感谢
